name: UPDATE

# Controls when the action will run. 
on: [issues, issue_comment]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Blog Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
          
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      
      #- name: Go Mod
      #  run: go mod tidy
          
      #- name: Build
      #  run: go build -o app main.go

      - name: Run
        run: |
          chmod 777 app
          ./app

      - name: Git config
        run: |
          git config user.name 'Roc-zhou'
          git config user.email 'roc.zhousir@gmaol.com'

      - name: Commit change
        run: |
          git checkout main
          git add .
          git commit -m "Update from Github Action"
      - name: Push
        env:
          GITHUB_LOGIN: Roc-zhou
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          mkdir -p ~/.ssh/
          echo "$GITHUB_TOKEN" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git push git@github.com:Roc-zhou/blog.git
      - name: Done
        run: echo 'done'

jobs:
  # This workflow contains a single job called "build"
  build:
    name: Roc Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
          
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      
      #- name: Go Mod
      #  run: go mod tidy
          
      #- name: Build
      #  run: go build -o app main.go

      - name: Clone
        env:
          GITHUB_LOGIN: Roc-zhou
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          mkdir -p ~/.ssh/
          echo "$GITHUB_TOKEN" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git clone git@github.com:Roc-zhou/Roc-zhou.git

      - name: Move and Run
        run: |
          mv ./app ./Roc-zhou
          chmod 777 app
          ./app

      - name: Git config
        run: |
          git config user.name 'Roc-zhou'
          git config user.email 'roc.zhousir@gmaol.com'

      - name: Commit change
        run: |
          git checkout main
          git add .
          git commit -m "Update from Github Action"
      - name: Push
        run: |
          git push git@github.com:Roc-zhou/Roc-zhou.git
      - name: Done
        run: echo 'done'